### ISSUE TITLE
type(s) of dependencies

### ISSUE THREAD

**Issue by soumasandesu** [wizardnet972/html-webpack-critical-plugin#1]
I cannot start the Webpack with your plugin. After some investigation, i see:

https://github.com/wizardnet972/critical-plugin/blob/1f4ea0da82635c8045c236df8cdcbda9d6247534/src/index.js#L3-L4

Since they will be used on webpack projects, is it more appropriate to set these dependencies as `devDependencies` + `peerDependencies`?

**Comment by wizardnet972** [comment]
@hkgsherlock 
- They are under `devDependencies` no?
- about `peerDependencies`, This plugin should work with any version of `chalk` nor `critical`, and you get them by `npm install`, are you agree?

> https://github.com/wizardnet972/critical-plugin/blob/1f4ea0da82635c8045c236df8cdcbda9d6247534/package.json#L50-L51
